from pizza_main import Ingredientes
"""INGREDIENTES PROTEÍNAS"""
class Proteinas(Ingredientes):
    pass
anchoas = Proteinas("Anchoas",1)
jamon_cocido = Proteinas("Jamón cocido",1)
jamon_serrano = Proteinas("Jamón Serrano",1)
chorizo_picante = Proteinas("Chorizo picante",1)
pollo_asado = Proteinas("Pollo asado",1)
speck = Proteinas("Speck",1)
atun = Proteinas("Atún",1)
guanciale = Proteinas("Guanciale",1)
salame = Proteinas("Salame",1)
salmon = Proteinas("Salmón",1)
salsa_trufa = Proteinas("Salsa trufa",1)
nutella = Proteinas("Nutella",1)
guanciale = Proteinas("Guanciale",1)
"""INGREDIENTES VERDURAS"""
class Verduras(Ingredientes):
    pass
muzzarella = Verduras("Muzzarella",0.5)
tomate = Verduras("Tomate",0.5)
tomate_cherry = Verduras("Tomate Cherry",0.5)
ajo = Verduras("Ajo",0.5)
oregano = Verduras("Orégano",0.5)
alcachofas = Verduras("Alcachofas",0.5)
aceitunas_negras = Verduras("Aceitunas Negras",0.5)
alcaparras = Verduras("Alcaparras",0.5)
patatas_al_horno = Verduras("Patatas al horno",0.5)
salsa_barbacoa = Verduras("Salsa barbacoa",0.5)
emmental = Verduras("Emmental",0.5)
grana_padano = Verduras("Grana padano",0.5)
gorgonzola = Verduras("Gorgonzola",0.5)
provola = Verduras("Próvola",0.5)
cebolla = Verduras("Cebolla",0.5)
berenjena = Verduras("Berenjena",0.5)
calcabacin = Verduras("Calabacin",0.5)
pimiento = Verduras("Pimiento",0.5)
pecorino_romano = Verduras("Pecorino romano",0.5)
huevo = Verduras("Huevo",0.5)
pimienta_negra = Verduras("Pimienta negra",0.5)
albahaca = Verduras("Albahaca",0.5)
panceta = Verduras("Panceta",0.5)
cebolla_morada = Verduras("Cebolla morada",0.5)
rucula = Verduras("Rúcula",0.5)
aceitunas = Verduras("Aceitunas",0.5)
nduja = Verduras("Nduja",0.5)
tomate_cherry_semi_seco = Verduras("Tomate cherry semi seco",0.5)
muzzarella_bufala = Verduras("Muzzarella bufala",0.5)
aguacate = Verduras("Aguacate",0.5)
lima = Verduras("Lima",0.5)
espinacas = Verduras("Espinacas",0.5)
rodajas_tomate = Verduras("Rodajas de tomate",0.5)
mayonesa = Verduras("Mayonesa",0.5)
azucar_glass = Verduras("Azúcar glass",0.5)
champiñones = Verduras("Champiñones",0.5)
